### ISSUE TITLE
Julia 0.5 running CodeTools

### ISSUE THREAD

**Issue by rapus95** [JuliaPackaging/Requires.jl#24] opened 2016-05-13 08:49 UTC
trying to run CodeTools ends up in this error:

```
ERROR: LoadError: InitError: type Method has no field func
 [inlined code] from C:\Users\necka\.julia\v0.5\Requires\src\Requires.jl:3
 in (::Requires.##8#9)() at C:\Users\necka\.julia\v0.5\Requires\src\init.jl:17
 in __init__() at C:\Users\necka\.julia\v0.5\Requires\src\init.jl:24
 in _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at .\loading.jl:174
 in _require_from_serialized(::Int64, ::Symbol, ::Bool) at .\loading.jl:202
 in require(::Symbol) at .\loading.jl:332
 in include_from_node1(::String) at .\loading.jl:426
 in eval(::Module, ::Any) at .\boot.jl:230
 [inlined code] from .\sysimg.jl:11
 in require(::Symbol) at .\loading.jl:357
 in eval(::Module, ::Any) at .\boot.jl:230
during initialization of module Requires
while loading C:\Users\necka\.julia\v0.5\CodeTools\src\CodeTools.jl, in expression starting on line 5
```

so while it happens when loading CodeTools it seems to happen exactly when Requires got to do something

**Comment by MikeInnes** [comment] 2016-05-16 21:49
What's your `Pkg.status()`?

**Comment by rapus95** [comment] 2016-05-17 17:33
```
3 required packages:
 - Atom                          0.4.2+             julia-0.5
 - CodeTools                     0.3.0+             julia-0.5
 - HttpServer                    0.1.5+             master (dirty)
46 additional packages:
 - ASTInterpreter                0.0.2
 - AbstractTrees                 0.0.2
 - BinDeps                       0.3.21
 - Blink                         0.3.4
 - Codecs                        0.1.5
 - ColorTypes                    0.2.2
 - Colors                        0.6.3
 - Compat                        0.7.17
 - DWARF                         0.0.2
 - Docile                        0.5.23
 - ELF                           0.0.2
 - FileIO                        0.0.5
 - FixedPointNumbers             0.1.3
 - FixedSizeArrays               0.1.0+             master
 - FreeType                      1.0.3              master
 - Gallium                       0.0.2
 - GeometryTypes                 0.1.4              master
 - Hiccup                        0.0.2
 - HttpCommon                    0.2.4
 - HttpParser                    0.1.1
 - JSON                          0.5.0
 - JuliaParser                   0.7.2+             master
 - LNR                           0.0.2
 - Lazy                          0.10.1
 - LibExpat                      0.1.2
 - MachO                         0.0.2
 - MacroTools                    0.3.0
 - MbedTLS                       0.2.2
 - Media                         0.1.2
 - MeshIO                        0.0.4+             master
 - Mustache                      0.0.14+            master
 - Mux                           0.2.0
 - Nettle                        0.2.3
 - ObjFileBase                   0.0.2
 - Packing                       0.0.4              master
 - Reactive                      0.3.2+             master
 - Reexport                      0.0.3
 - Requires                      0.2.2
 - SHA                           0.1.2
 - StructIO                      0.0.2
 - TerminalUI                    0.0.1
 - URIParser                     0.1.3
 - VT100                         0.0.1
 - WebSockets                    0.1.2
 - WinRPM                        0.1.15
 - Zlib                          0.1.12
```

**Comment by MikeInnes** [comment] 2016-05-17 17:56
Ah right, didn't see that you're on 0.5. Pkg.checkout("Requires") should do the trick.

**Comment by rapus95** [comment] 2016-05-17 18:02
Damn now I'm running into this:

```
WARNING: Module Compat uuid did not match cache file
  This is likely because module Compat does not support  precompilation but is imported by a module that does.
ERROR: LoadError: LoadError: __precompile__(true) but require failed to create a precompiled cache file
 in require(::Symbol) at .\loading.jl:366
 in include_from_node1(::String) at .\loading.jl:426
 in eval(::Module, ::Any) at .\boot.jl:230
 [inlined code] from .\sysimg.jl:11
 in require(::Symbol) at .\loading.jl:357
 in include_from_node1(::String) at .\loading.jl:426
 in eval(::Module, ::Any) at .\boot.jl:230
 [inlined code] from .\sysimg.jl:11
 in require(::Symbol) at .\loading.jl:357
 in eval(::Module, ::Any) at .\boot.jl:230
while loading C:\Users\necka\.julia\v0.5\LNR\src\LNR.jl, in expression starting on line 4
while loading C:\Users\necka\.julia\v0.5\CodeTools\src\CodeTools.jl, in expression starting on line 5
```

Though you don't need to help me here since I'm not sure that it is Requires' fault anymore

**Comment by MikeInnes** [comment] 2016-05-17 18:04
Does this happen repeatedly? Sometimes I get things like this in Julia and just have to try again.

**Comment by rapus95** [comment] 2016-05-17 18:13
Sorry for wasting your time like that -.- Resulting again ends up there:

```
ERROR: LoadError: JuliaParser.Diagnostics.Diagnostic([JuliaParser.Diagnostics.Message(:error,JuliaParser.Tokens.SourceRange(0xffffffff,0x0000ffff,0xff),"invalid character \"\r\"")])
 [inlined code] from C:\Users\necka\.julia\v0.5\JuliaParser\src\diagnostics.jl:15
 in next_token(::JuliaParser.Lexer.TokenStream{JuliaParser.Tokens.Token}, ::Bool) at C:\Users\necka\.julia\v0.5\JuliaParser\src\lexer.jl:853
 in peek_token(::JuliaParser.Lexer.TokenStream{JuliaParser.Tokens.Token}, ::Bool) at C:\Users\necka\.julia\v0.5\JuliaParser\src\lexer.jl:882
 in parse_Nary(::JuliaParser.Parser.ParseState, ::JuliaParser.Lexer.TokenStream{JuliaParser.Tokens.Token}, ::JuliaParser.Parser.##4#5, ::Set{Char}, ::Symbol, ::Set{Symbol}, ::Bool, ::Void) at C:\Users\necka\.julia\v0.5\JuliaParser\src\parser.jl:333
 in parse_resword(::JuliaParser.Parser.ParseState, ::JuliaParser.Lexer.TokenStream{JuliaParser.Tokens.Token}, ::JuliaParser.Tokens.Token, ::Void) at C:\Users\necka\.julia\v0.5\JuliaParser\src\parser.jl:1113
 in parse_call(::JuliaParser.Parser.ParseState, ::JuliaParser.Lexer.TokenStream{JuliaParser.Tokens.Token}) at C:\Users\necka\.julia\v0.5\JuliaParser\src\parser.jl:691
 in parse_decl(::JuliaParser.Parser.ParseState, ::JuliaParser.Lexer.TokenStream{JuliaParser.Tokens.Token}) at C:\Users\necka\.julia\v0.5\JuliaParser\src\parser.jl:561
 in parse_factorh(::JuliaParser.Parser.ParseState, ::JuliaParser.Lexer.TokenStream{JuliaParser.Tokens.Token}, ::JuliaParser.Parser.#parse_decl, ::Set{Symbol}) at C:\Users\necka\.julia\v0.5\JuliaParser\src\parser.jl:584
 in parse_unary(::JuliaParser.Parser.ParseState, ::JuliaParser.Lexer.TokenStream{JuliaParser.Tokens.Token}) at C:\Users\necka\.julia\v0.5\JuliaParser\src\parser.jl:621
 in parse_with_chains(::JuliaParser.Parser.ParseState, ::JuliaParser.Lexer.TokenStream{JuliaParser.Tokens.Token}, ::JuliaParser.Parser.#parse_rational, ::Set{Symbol}, ::Symbol) at C:\Users\necka\.julia\v0.5\JuliaParser\src\parser.jl:206 (repeats 2 times)
 in parse_range(::JuliaParser.Parser.ParseState, ::JuliaParser.Lexer.TokenStream{JuliaParser.Tokens.Token}) at C:\Users\necka\.julia\v0.5\JuliaParser\src\parser.jl:503
 [inlined code] from .\operators.jl:39
 in parse_comparison(::JuliaParser.Parser.ParseState, ::JuliaParser.Lexer.TokenStream{JuliaParser.Tokens.Token}, ::Set{Symbol}) at C:\Users\necka\.julia\v0.5\JuliaParser\src\parser.jl:457
 in parse_RtoL(::JuliaParser.Parser.ParseState, ::JuliaParser.Lexer.TokenStream{JuliaParser.Tokens.Token}, ::JuliaParser.Parser.#parse_and, ::Set{Symbol}) at C:\Users\necka\.julia\v0.5\JuliaParser\src\parser.jl:426
 [inlined code] from .\operators.jl:39
 in parse_or(::JuliaParser.Parser.ParseState, ::JuliaParser.Lexer.TokenStream{JuliaParser.Tokens.Token}) at C:\Users\necka\.julia\v0.5\JuliaParser\src\parser.jl:417
 in parse_RtoL(::JuliaParser.Parser.ParseState, ::JuliaParser.Lexer.TokenStream{JuliaParser.Tokens.Token}, ::JuliaParser.Parser.#parse_or, ::Set{Symbol}) at C:\Users\necka\.julia\v0.5\JuliaParser\src\parser.jl:239
 [inlined code] from .\operators.jl:39
 in parse_arrow(::JuliaParser.Parser.ParseState, ::JuliaParser.Lexer.TokenStream{JuliaParser.Tokens.Token}) at C:\Users\necka\.julia\v0.5\JuliaParser\src\parser.jl:431
 [inlined code] from .\operators.jl:39
 in parse_cond(::JuliaParser.Parser.ParseState, ::JuliaParser.Lexer.TokenStream{JuliaParser.Tokens.Token}) at C:\Users\necka\.julia\v0.5\JuliaParser\src\parser.jl:270
 in parse_Nary(::JuliaParser.Parser.ParseState, ::JuliaParser.Lexer.TokenStream{JuliaParser.Tokens.Token}, ::JuliaParser.Parser.#parse_cond, ::Set{Char}, ::Symbol, ::Set{Any}, ::Bool, ::Void) at C:\Users\necka\.julia\v0.5\JuliaParser\src\parser.jl:310
 [inlined code] from C:\Users\necka\.julia\v0.5\JuliaParser\src\parser.jl:399
 in parse_docstring(::JuliaParser.Parser.ParseState, ::JuliaParser.Lexer.TokenStream{JuliaParser.Tokens.Token}, ::JuliaParser.Parser.#parse_eq) at C:\Users\necka\.julia\v0.5\JuliaParser\src\parser.jl:2106
 in parse_Nary(::JuliaParser.Parser.ParseState, ::JuliaParser.Lexer.TokenStream{JuliaParser.Tokens.Token}, ::JuliaParser.Parser.##1#2, ::Set{Char}, ::Symbol, ::Set{Char}, ::Bool, ::Void) at C:\Users\necka\.julia\v0.5\JuliaParser\src\parser.jl:310
 in parse_stmts(::JuliaParser.Parser.ParseState, ::JuliaParser.Lexer.TokenStream{JuliaParser.Tokens.Token}) at C:\Users\necka\.julia\v0.5\JuliaParser\src\parser.jl:367
 in #parse#24(::JuliaParser.Parser.#parse_stmts, ::Function, ::JuliaParser.Lexer.TokenStream{JuliaParser.Tokens.Token}) at C:\Users\necka\.julia\v0.5\JuliaParser\src\parser.jl:2141
 in _precompile_() at C:\Users\necka\.julia\v0.5\JuliaParser\src\precompile.jl:7
 in include_from_node1(::String) at .\loading.jl:426
 [inlined code] from .\boot.jl:230
 in anonymous at .\<no file>:4294967295
 in eval(::Module, ::Any) at .\boot.jl:230
 [inlined code] from .\sysimg.jl:11
 in process_options(::Base.JLOptions) at .\client.jl:240
 in _start() at .\client.jl:319
while loading C:\Users\necka\.julia\v0.5\JuliaParser\src\JuliaParser.jl, in expression starting on line 12
ERROR: LoadError: LoadError: LoadError: Failed to precompile JuliaParser to C:\Users\necka\.julia\lib\v0.5\JuliaParser.ji
 [inlined code] from .\error.jl:21
 in compilecache(::String) at .\loading.jl:505
 in require(::Symbol) at .\loading.jl:337
 in include_from_node1(::String) at .\loading.jl:426 (repeats 3 times)
 [inlined code] from .\boot.jl:230
 in anonymous at .\<no file>:4294967295
 in eval(::Module, ::Any) at .\boot.jl:230
 [inlined code] from .\sysimg.jl:11
 in process_options(::Base.JLOptions) at .\client.jl:240
 in _start() at .\client.jl:319
while loading C:\Users\necka\.julia\v0.5\CodeTools\src\parse\scope.jl, in expression starting on line 6
while loading C:\Users\necka\.julia\v0.5\CodeTools\src\parse/parse.jl, in expression starting on line 1
while loading C:\Users\necka\.julia\v0.5\CodeTools\src\CodeTools.jl, in expression starting on line 10
ERROR: LoadError: LoadError: Failed to precompile CodeTools to C:\Users\necka\.julia\lib\v0.5\CodeTools.ji
 [inlined code] from .\error.jl:21
 in compilecache(::String) at .\loading.jl:505
 in require(::Symbol) at .\loading.jl:337
 in include_from_node1(::String) at .\loading.jl:426 (repeats 2 times)
 [inlined code] from .\boot.jl:230
 in anonymous at .\<no file>:4294967295
 in eval(::Module, ::Any) at .\boot.jl:230
 [inlined code] from .\sysimg.jl:11
 in process_options(::Base.JLOptions) at .\client.jl:240
 in _start() at .\client.jl:319
while loading C:\Users\necka\.julia\v0.5\Atom\src\eval.jl, in expression starting on line 1
while loading C:\Users\necka\.julia\v0.5\Atom\src\Atom.jl, in expression starting on line 10
ERROR: Failed to precompile Atom to C:\Users\necka\.julia\lib\v0.5\Atom.ji
 [inlined code] from .\error.jl:21
 in compilecache(::String) at .\loading.jl:505
 in require(::Symbol) at .\loading.jl:364
 in require(::Symbol) at C:\Users\necka\.julia\v0.5\Requires\src\require.jl:10
 in eval(::Module, ::Any) at .\boot.jl:230
```

**Comment by juliohm** [comment] 2016-05-20 16:48
My Travis build is failing with the same error on Julia v0.5: https://travis-ci.org/juliohm/ImageQuilting.jl/jobs/131734614

**Comment by juliohm** [comment] 2016-05-24 08:01
@MikeInnes are you working on this issue?

**Comment by MikeInnes** [comment] 2016-05-24 16:42
@rapus95 I'm not sure, but it doesn't look like that's a requires issue – JuliaParser and Base have undergone a lot of changes recently so they may be out of sync, see if it loads on its own and debug from there I think.

@juliohm in the sense of getting stuff working on 0.5, sure, but 0.5 is also still changing so it makes less sense to tag a release at this point. However, you can use the same fix in travis, just Pkg.checkout("Requires") in the travis test script.

**Comment by juliohm** [comment] 2016-05-24 16:44
Thank you Mike, I'll wait for the next tag. :)

-Júlio

**Comment by juliohm** [comment] 2016-07-26 02:23
@MikeInnes do you have any idea of the current status?

I never had a build failure for such a long period, I wonder why the issue is taking so long to be fixed in the Julia language and why my package is affected by it whereas many other packages are building just fine in Julia v0.5.

I am not using `Requires.jl` myself, maybe the issue is coming from one of my dependencies?

**Comment by asbisen** [comment] 2016-08-07 05:56
Just an update checking out `master` for `Requires.jl` works on `julia-rc1`. The only issue I had was that `Pkg.checkout()` failed to merge the code so I had to manually go inside `~/.julia/v0.5/Requires` and perform a `git pull`

**Comment by timholy** [comment] 2021-12-13 18:00
This is probably too outdated to be useful.

**Closed by timholy** 2021-12-13 18:00 UTC
